import { Check, CircleDollarSign, Play } from 'lucide-react';
import { Badge, Button, Card } from '../common';
import { useUiLanguage } from '../../contexts/UiLanguageContext';
import type { TradeDeskPlan, UpdateTradePlanRequest, TradePosition } from '../../types/tradeDesk';
import { ModeBadge } from './AnswerParts';
import { formatMoney, formatDate } from './deskFormat';

export function PositionCard({ position, plans, onPaperFill, onManualFill, onReconcile, onSettle, onUpdatePlan }: { position: TradePosition; plans: TradeDeskPlan[]; onPaperFill: (position: TradePosition) => void; onManualFill: (position: TradePosition) => void; onReconcile: (position: TradePosition) => void; onSettle: (position: TradePosition) => void; onUpdatePlan: (planId: string, changes: UpdateTradePlanRequest) => void }) {
  const { t } = useUiLanguage();
  const plan = plans.find((item) => item.id === position.planId) || position.plan;
  const replay = plan?.dataMode === 'replay';
  return <Card variant="bordered" padding="md"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold text-foreground">{position.underlying}</h3><Badge variant={position.ledger === 'paper' ? 'info' : 'warning'}>{position.ledger === 'paper' ? t('tradeDesk.paper') : t('tradeDesk.manualLive')}</Badge>{plan ? <ModeBadge mode={plan.dataMode} /> : null}</div><p className="mt-1 text-xs text-secondary-text">Plan {position.planId} · {t('tradeDesk.positionStatus')}: {position.status}</p></div><div className="flex flex-wrap gap-2">{position.ledger === 'paper' ? <Button size="sm" variant="outline" onClick={() => onPaperFill(position)}><Play className="h-3.5 w-3.5" />{t('tradeDesk.paperFill')}</Button> : <Button size="sm" variant="outline" onClick={() => onManualFill(position)} disabled={replay}><CircleDollarSign className="h-3.5 w-3.5" />{t('tradeDesk.manualFill')}</Button>}{position.status === 'reconciliation_required' ? (position.ledger === 'paper'
      // Paper plans cannot record broker exercise/assignment; expired legs settle at intrinsic value.
      ? <Button size="sm" variant="secondary" onClick={() => onSettle(position)}><Check className="h-3.5 w-3.5" />Settle expiry</Button>
      : <Button size="sm" variant="secondary" onClick={() => onReconcile(position)}><Check className="h-3.5 w-3.5" />Reconcile</Button>) : null}{plan && position.status !== 'closed' ? <Button size="sm" variant="ghost" onClick={() => onUpdatePlan(plan.id, { monitoring: !plan.monitoring })}>{plan.monitoring ? 'Pause alerts' : 'Resume alerts'}</Button> : null}{plan && position.status === 'watching' && plan.status !== 'archived' ? <Button size="sm" variant="ghost" onClick={() => onUpdatePlan(plan.id, { status: 'archived', monitoring: false })}>Archive</Button> : null}</div></div><div className="mt-4 overflow-x-auto rounded-xl border border-border/50"><table className="w-full min-w-[600px] text-left text-xs"><thead className="bg-elevated/50 text-secondary-text"><tr><th className="px-3 py-2">{t('tradeDesk.contract')}</th><th className="px-3 py-2">Qty</th><th className="px-3 py-2">Average</th><th className="px-3 py-2">Mark</th><th className="px-3 py-2">P&L</th></tr></thead><tbody>{position.legs.map((leg) => <tr key={leg.contractId} className="border-t border-border/40"><td className="px-3 py-2 font-mono text-foreground">{leg.contractId}<span className="ml-2 text-secondary-text">{leg.right}</span></td><td className="px-3 py-2 text-foreground">{leg.signedQuantity || leg.quantity} × {leg.multiplier}</td><td className="px-3 py-2 text-foreground">{formatMoney(leg.averagePrice)}</td><td className="px-3 py-2 text-foreground">{formatMoney(leg.markPrice)}</td><td className="px-3 py-2 text-foreground">{formatMoney(leg.unrealizedPnl)}</td></tr>)}</tbody></table></div><div className="mt-3 grid gap-2 sm:grid-cols-4 text-sm"><div><span className="block text-xs text-secondary-text">{t('tradeDesk.realizedPnl')}</span><strong className="text-foreground">{formatMoney(position.realizedPnl)}</strong></div><div><span className="block text-xs text-secondary-text">{t('tradeDesk.unrealizedPnl')}</span><strong className="text-foreground">{formatMoney(position.unrealizedPnl)}</strong></div><div><span className="block text-xs text-secondary-text">{t('tradeDesk.fees')}</span><strong className="text-foreground">{formatMoney(position.fees)}</strong></div><div><span className="block text-xs text-secondary-text">{t('tradeDesk.valuation')}</span><strong className="text-foreground">{position.valuationStatus || t('tradeDesk.unknown')}</strong>{position.valuationAt ? <span className="ml-1 text-xs font-normal text-muted-text">({formatDate(position.valuationAt)})</span> : null}</div></div>{replay ? <p className="mt-3 text-xs text-warning">{t('tradeDesk.manualLiveReplayDisabled')}</p> : null}</Card>;
}
